### ISSUE TITLE
install ALB ingress controller  via cdk8s construct library :)

### ISSUE THREAD

**Issue by neilkuan** [SbgMartin/aws-cdk-eks-gitops-example#3]
https://github.com/SbgMartin/aws-cdk-eks-gitops-example/blob/74bd3beb55d32ea1d525bb7435fe980f3def4101/lib/k8s-addon-alb-ingress-controller/k8s-alb-ingress-controller.ts#L16-L100

How about this [cdk8s-aws-alb-ingress-controller](https://github.com/guan840912/cdk8s-aws-alb-ingress-controller) ?

😊 😊 😊

**Comment by SbgMartin** [comment]
Hi @guan840912 , thanks for pointing me to it. I'll check it out.
